// Pure-JS globals a bare engine (QuickJS) lacks. On-device these come from the
// engine/WebView or a polyfill package; here we inject minimal versions.
(function(){
  function b64ToU8(b64){var C='ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/';b64=String(b64).replace(/=+$/,'');var out=[],bits=0,val=0;for(var i=0;i<b64.length;i++){var idx=C.indexOf(b64[i]);if(idx<0)continue;val=(val<<6)|idx;bits+=6;if(bits>=8){bits-=8;out.push((val>>bits)&255);}}return new Uint8Array(out);}
  if(typeof globalThis.TextEncoder==='undefined')globalThis.TextEncoder=class{encode(s){s=String(s);var b=[];for(var i=0;i<s.length;i++){var c=s.charCodeAt(i);if(c<128)b.push(c);else if(c<2048)b.push(192|c>>6,128|c&63);else b.push(224|c>>12,128|c>>6&63,128|c&63);}return new Uint8Array(b);}};
  if(typeof globalThis.TextDecoder==='undefined')globalThis.TextDecoder=class{decode(u){var a=u instanceof Uint8Array?u:new Uint8Array(u||[]),s='';for(var i=0;i<a.length;){var c=a[i++];if(c>=240){c=(c&7)<<18|(a[i++]&63)<<12|(a[i++]&63)<<6|a[i++]&63;}else if(c>=224){c=(c&15)<<12|(a[i++]&63)<<6|a[i++]&63;}else if(c>=192){c=(c&31)<<6|a[i++]&63;}s+=String.fromCodePoint(c);}return s;}};
  if(typeof globalThis.Buffer==='undefined')globalThis.Buffer={from:function(d,enc){if(enc==='base64')return b64ToU8(d);if(typeof d==='string')return new globalThis.TextEncoder().encode(d);return new Uint8Array(d);},isBuffer:function(){return false;}};
  if(typeof globalThis.URL==='undefined')globalThis.URL=class{constructor(u){this.href=String(u);var m=/^([a-z]+:)?(\/\/[^/?#]*)?([^?#]*)(\?[^#]*)?(#.*)?$/i.exec(this.href)||[];this.protocol=m[1]||'';this.host=(m[2]||'').replace(/^\/\//,'');this.pathname=m[3]||'/';this.search=m[4]||'';this.hash=m[5]||'';this.searchParams={get(){return null;},has(){return false;}};}};
})();
(function(){ if(typeof globalThis.process==='undefined')globalThis.process={env:{},argv:[],platform:'',version:'v0',versions:{},cwd:function(){return '/';},nextTick:function(f){Promise.resolve().then(f);},stdout:{write:function(){}},stderr:{write:function(){}}}; })();
(function(){ if(typeof globalThis.crypto==='undefined')globalThis.crypto={ subtle:{}, getRandomValues:function(a){for(var i=0;i<a.length;i++)a[i]=(Math.imul(i+1,2654435761)>>>0)&255;return a;} }; })();
